### ISSUE TITLE
Provide template for gitlab CI

### ISSUE THREAD

**Issue by guineveresaenger** [samsung-cnct/solas-container#17]
Create a .gitlab-ci.yml similar to : https://github.com/samsung-cnct/container-fluent-bit/issues/11

Helpful samples:
https://github.com/samsung-cnct/cyklops-events/pull/7/files
https://git.cnct.io/venezia/install-mongodb/blob/master/.gitlab-ci.yml

**Comment by guineveresaenger** [comment]
ToReview:

- Added gitlab-ci.yml template to solas-container: https://github.com/samsung-cnct/solas-container/pull/18
- Updated linked reference docs in solas: https://github.com/samsung-cnct/solas/pull/33

Things to consider:
- Since ultimate integration with gitlab is still pending, the instructions on how to add a newly created repository to gitlab are still missing. Possibly wait until that is done?
- There will also be some discussion on how to handle version tags that may or may not affect the way the `publish` stage should look.
- A (pending integration) working example lives [here](https://github.com/samsung-cnct/container-fluent-bit/pull/12).

**Comment by leahnp** [comment]
@guineveresaenger I think this is looking good and we should start merging/closing stuff today. If it develops like the original `solas` work, the next few ports to GitLab will probably result in more tweaks and clarifications to the instructions. I would be interested to do a port today!

**Comment by guineveresaenger** [comment]
Fixed by https://github.com/samsung-cnct/solas-container/pull/18
